### ISSUE TITLE
Add font generator utility

### ISSUE THREAD

**Issue by tehKaiN** [AmigaPorts/ACE#44]
Currently, I have php script for generating ACE fonts, but it's inconvenient and not portable way to do this. It needs C implementation without too many dependencies - should be working directly on ttf/otf and some popular bitmap font formats.

Perhaps it would be wise to use freetype amalgamated lib?

---

## TODO

- [x] Generate 1bpp bitmap glyphs, each in separate PNG file, based on TTF
- [x] Generate ACE packed font in PNG file
- [x] Organize app so that it can use either TTF or PNGs as source
- [x] implement `glyphsFromDir()`
- [x] Generate ACE packed font
- [x] Add parameters for CLI & help screen

**Comment by tehKaiN** [comment]
I thought that it could be done with STB single-file libs, but I think that freetype is better way to go. There are amalgamated versions of this lib, so those take care of limiting external dependencies

**Comment by tehKaiN** [comment]
this tool should not only allow generating font from passed ttf + set of chars, but also to generate intermediate directory with bitmap glyps and later to produce font from it in separate step. This way one can generate bitmap font, tweak chars in gfx app or add custom glyphs, then continue font baking from modified files.

**Comment by tehKaiN** [comment]
This will collide with #69 since it will need bitmap_conv for its internal use. I will restructure related code in similar fashion as font_conv
